# Generated by Django 3.0.7 on 2020-06-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.ImageField(null=True, upload_to='departments/', verbose_name='Фото'),
        ),
    ]
