# Generated by Django 3.0.7 on 2020-06-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200619_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Position', verbose_name='Должность пользователя'),
        ),
    ]
