# Generated by Django 3.0.7 on 2020-06-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentWithTitle',
        ),
    ]
