# Generated by Django 3.0.7 on 2020-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_commentwithtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField()),
            ],
            options={
                'verbose_name': 'Группа Тэгов',
                'verbose_name_plural': 'Группы Тэгов',
            },
        ),
    ]
