# Generated by Django 3.0.7 on 2020-06-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200621_0306'),
        ('blog', '0002_idea_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department'),
        ),
    ]
