# Generated by Django 3.0.7 on 2020-06-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_idea_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='photo',
            field=models.ImageField(null=True, upload_to='ideas/', verbose_name='Фото'),
        ),
    ]
